### ISSUE TITLE
“2020-01-07-regex-and-dfa.md”文件内“|”符号未转义

### ISSUE THREAD

**Issue by LettuceBacon** [houbb/houbb.github.io#3]
您对比一下就知道了，主要是符号“|”没有转义
- https://houbb.github.io/2020/01/07/regex-and-dfa
- https://github.com/houbb/houbb.github.io/blob/master/_posts/2020-01-07-regex-and-dfa.md

**Comment by houbb** [comment]
感谢提醒，已修复。
